default:  fxctmp9_tmp\eyes_flashlight_vs30.inc shaders\fxc\eyes_flashlight_vs30.vcs fxctmp9_tmp\eyes_flashlight_ps30.inc shaders\fxc\eyes_flashlight_ps30.vcs fxctmp9_tmp\flashlight_ps30.inc shaders\fxc\flashlight_ps30.vcs fxctmp9_tmp\teeth_flashlight_vs30.inc shaders\fxc\teeth_flashlight_vs30.vcs fxctmp9_tmp\teeth_flashlight_ps30.inc shaders\fxc\teeth_flashlight_ps30.vcs

fxctmp9_tmp\eyes_flashlight_vs30.inc shaders\fxc\eyes_flashlight_vs30.vcs: eyes_flashlight_vs20.fxc common_fxc.h common_vs_fxc.h common_pragmas.h common_hlsl_cpp_consts.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." eyes_flashlight_vs20.fxc-----eyes_flashlight_vs30
	echo eyes_flashlight_vs20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt

fxctmp9_tmp\eyes_flashlight_ps30.inc shaders\fxc\eyes_flashlight_ps30.vcs: eyes_flashlight_ps2x.fxc eyes_flashlight_inc.fxc common_ps_fxc.h common_flashlight_fxc.h common_pragmas.h common_fxc.h shader_constant_register_map.h common_hlsl_cpp_consts.h common_vertexlitgeneric_dx9.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." eyes_flashlight_ps2x.fxc-----eyes_flashlight_ps30
	echo eyes_flashlight_ps2x.fxc>> filestocopy.txt
	echo eyes_flashlight_inc.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt

fxctmp9_tmp\flashlight_ps30.inc shaders\fxc\flashlight_ps30.vcs: flashlight_ps2x.fxc 
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." flashlight_ps2x.fxc-----flashlight_ps30
	echo flashlight_ps2x.fxc>> filestocopy.txt

fxctmp9_tmp\teeth_flashlight_vs30.inc shaders\fxc\teeth_flashlight_vs30.vcs: teeth_flashlight_vs20.fxc vortwarp_vs20_helper.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." teeth_flashlight_vs20.fxc-----teeth_flashlight_vs30
	echo teeth_flashlight_vs20.fxc>> filestocopy.txt
	echo vortwarp_vs20_helper.h>> filestocopy.txt

fxctmp9_tmp\teeth_flashlight_ps30.inc shaders\fxc\teeth_flashlight_ps30.vcs: teeth_flashlight_ps2x.fxc common_pragmas.h common_fxc.h shader_constant_register_map.h common_hlsl_cpp_consts.h common_vertexlitgeneric_dx9.h common_ps_fxc.h common_flashlight_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." teeth_flashlight_ps2x.fxc-----teeth_flashlight_ps30
	echo teeth_flashlight_ps2x.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt

